import { Database } from "./autogenerated";

export type User = Database["public"]["Tables"]["users"]["Row"];
export type Workspace = Database["public"]["Tables"]["workspaces"]["Row"];
export type Member = Database["public"]["Tables"]["workspace_members"]["Row"];
export type Directory = Database["public"]["Tables"]["directories"]["Row"];
export type Bookmark = Database["public"]["Tables"]["bookmarks"]["Row"];
export type { Database };
