import { useRouter } from "next/router";
import React from "react";
import {
  Button,
  Container,
  Flex,
  Grid,
  LoadingOverlay,
  Text,
  TextInput,
  Title,
} from "@mantine/core";
import { useSupabaseClient, useUser } from "@supabase/auth-helpers-react";
import { Database } from "@/common/autogenerated";
import { useProfile } from "@/context/profileContext";

const WorkspaceView = () => {
  const supabaseClient = useSupabaseClient<Database>();
  const profile = useProfile();
  const [value, setValue] = React.useState("");

  return (
    <Container>
      <Title>Create new workspace</Title>
      <Flex
        sx={{
          padding: "2em",
          gap: "1em",
        }}
      >
        <TextInput
          value={value}
          placeholder="Workspace name"
          onChange={(event) => setValue(event.currentTarget.value)}
        />
        <Button
          onClick={async () => {
            await supabaseClient.from("workspaces").insert({
              name: value,
            } as any);
            profile.refetch();
          }}
        >
          Create
        </Button>
      </Flex>
    </Container>
  );
};

export default WorkspaceView;
